### ISSUE TITLE
What should be Komikku's content raiting?

### ISSUE THREAD

**Issue by libreajans** [flathub/info.febvre.Komikku#84]
Hi @bilelmoussaoui and @ebassi 

Komikku is a Manga and Cartoon reader. 

I sent a PR for correcting content ratings there (https://gitlab.com/valos/Komikku/-/merge_requests/173)

But the developer thinks it's just a browser and does not contain any content.

Based on your knowledge what should be Komikku's content rating?

**Comment by bilelmoussaoui** [comment]
I agree with the author says, it is similar to the content rating of a browser and content apps like steam for example
