### ISSUE TITLE
Missing certain icons on KDE Wayland EndeavourOS

### ISSUE THREAD

**Issue by notkeftie** [flathub/info.febvre.Komikku#98]
Various icons as shown below seem to be missing on my KDE Wayland in EndeavourOS:

![image](https://user-images.githubusercontent.com/101351551/215619239-53f5dc2b-d571-404d-a52b-fea16d14efca.png)
----
![image](https://user-images.githubusercontent.com/101351551/215619326-e77bf580-26e1-470a-9651-3f62a5e55521.png)
----
![image](https://user-images.githubusercontent.com/101351551/215619341-8644851e-2758-48b9-9241-fc4526e1c0fc.png)
----
Debug Info:

[Komikku-debug-info.txt](https://github.com/flathub/info.febvre.Komikku/files/10540831/Komikku-debug-info.txt)

**Comment by valos** [comment]
It seems that adwaita-icon-theme package is missing.

This is not the right place to make an issue. This is not the Komikku repo. It's just a repo allowing the construction of Flatpak packages of Komikku.

The correct place is https://gitlab.com/valos/Komikku/-/issues

**Comment by notkeftie** [comment]
I had thought it was a flatpak specific issue but I do see that it does indeed happen on the normal package too so I will close this.
